name: "打卡"

# 明确触发条件
on:
  workflow_dispatch: # 手动触发
  schedule:
    # 每天 UTC 00:00 (北京时间 08:00) 触发，然后脚本内随机延迟执行
    - cron: "0 0 * * *"

# 配置并发控制，避免任务重叠执行
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # 超时时间需要增加，因为包含了随机延迟。9小时延迟 + 任务执行时间。设置为600分钟（10小时）。
    timeout-minutes: 600

    permissions:
      actions: write
      contents: read

    steps:
      # 随机延迟，范围 0-9 小时 (0-32400 秒)
      # 这会使实际执行时间落在北京时间 8:00 到 17:00 之间
      - name: Random Delay
        run: |
          DELAY=$(shuf -i 0-32400 -n 1)
          echo "Workflow triggered. Waiting for ${DELAY} seconds before running the main script..."
          sleep $DELAY

      # 设置时区为 Asia/Shanghai
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # 优化克隆深度

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # 启用 pip 缓存
          check-latest: true # 检查是否有更新的补丁版本

      # 缓存 pip 依赖
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 执行任务
      - name: Run sign in script
        env:
          USER: ${{ secrets.USER }}
          TZ: Asia/Shanghai # 确保脚本运行时也使用正确的时区
        run: |
          python main.py

      - name: Clean up workflow runs
        if: always()
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
